Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: payan-example-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html